seed: 42                                  # Define the random seed for consistent results.
mlflow: false                             # Switch to turn on/off mlflow for experiment tracking.
paths:                                    #
    data: ./data/                         # Where the data is stored.
    results: ./results/                   # Where the results such as trained model, and plots will be saved.
unsupervised:                             #
    model_mode: cpc                      # If there are multiple models, define which one to use.
unlabelled_data: True                     # If True, training loader can use all unlabelled data in addition to labelled ones
                                          # Else, it will only use labelled training data
